# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfcfbedd9cb0027b5843429a3d3011922b58dae608e807016300b3cc8aec84f58690f5a5394b70c83d3984bd89e13d7393daf0079c3686afb74ce163389ab93e

test:
  secret_key_base: 830a5fce2a85dd3a002c2c8c65961c7c5c43c4382a7df44698dd6c49b8bfd00a3054b0885150587e8072c4e0e6da9e5240d73c364b56065811817dc94807b895

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
